// <auto-generated />
using System;
using AnaDron.SDTest.SqlDataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace SqlDataAccess.Migrations
{
    [DbContext(typeof(SystemContext))]
    [Migration("20190321171909_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AnaDron.SDTest.SqlDataAccess.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount");

                    b.Property<DateTime>("DT");

                    b.Property<int>("PayeeId");

                    b.Property<int>("RecepientId");

                    b.HasKey("TransactionId");

                    b.HasIndex("PayeeId");

                    b.HasIndex("RecepientId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("AnaDron.SDTest.SqlDataAccess.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Balance");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AnaDron.SDTest.SqlDataAccess.Transaction", b =>
                {
                    b.HasOne("AnaDron.SDTest.SqlDataAccess.User", "Payee")
                        .WithMany("OutputTransactions")
                        .HasForeignKey("PayeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AnaDron.SDTest.SqlDataAccess.User", "Recepient")
                        .WithMany("InputTransactions")
                        .HasForeignKey("RecepientId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
